# Generated by Django 5.2.17 on 2026-09-23 16:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Активно'), ('paused', 'Приостановлено'), ('completed', 'Завершено')], default='active', max_length=16)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curated_enrollments', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='courses.courserevision')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-assigned_at',),
            },
        ),
        migrations.CreateModel(
            name='StepQuestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answered_step_questions', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='learning.enrollment')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='courses.steprevision')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='step_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('checking', 'Проверяется'), ('pending_review', 'Ожидает куратора'), ('accepted', 'Принято'), ('incorrect', 'Неверно'), ('returned', 'Возвращено'), ('error', 'Ошибка проверки')], default='queued', max_length=24)),
                ('payload', models.JSONField(default=dict)),
                ('artifact_file', models.FileField(blank=True, null=True, upload_to='submissions/%Y/%m/')),
                ('artifact_url', models.URLField(blank=True, max_length=1000)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('safe_diagnostics', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(blank=True, max_length=128)),
                ('idempotency_scope', models.CharField(blank=True, max_length=255)),
                ('request_hash', models.CharField(blank=True, max_length=64)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='learning.enrollment')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='courses.steprevision')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('accepted', 'Принято'), ('returned', 'Возвращено')], max_length=16)),
                ('comment', models.TextField(blank=True)),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='learning.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('revision', 'student'), name='unique_student_revision_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('enrollment', 'step', 'attempt_number'), name='unique_submission_attempt'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('student', 'idempotency_scope', 'idempotency_key'), name='unique_submission_idempotency_key'),
        ),
    ]
