# Generated by Django 5.2.17 on 2026-09-25 17:20

import django.db.models.deletion
import uuid
from django.utils import timezone
from django.conf import settings
from django.db import migrations, models


def migrate_existing_threads(apps, schema_editor):
    StepQuestion = apps.get_model("learning", "StepQuestion")
    StepQuestionMessage = apps.get_model("learning", "StepQuestionMessage")
    batch = []
    for question in StepQuestion.objects.select_related("student", "answered_by", "enrollment").iterator():
        batch.append(StepQuestionMessage(
            question_id=question.pk, sender_id=question.student_id, body=question.question,
            created_at=question.created_at, updated_at=question.created_at,
        ))
        if question.answer:
            batch.append(StepQuestionMessage(
                question_id=question.pk,
                sender_id=question.answered_by_id or question.enrollment.curator_id,
                body=question.answer,
                created_at=question.answered_at or question.updated_at or timezone.now(),
                updated_at=question.answered_at or question.updated_at or timezone.now(),
            ))
        if len(batch) >= 1000:
            StepQuestionMessage.objects.bulk_create(batch)
            batch = []
    if batch:
        StepQuestionMessage.objects.bulk_create(batch)


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StepQuestionMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='learning.stepquestion')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='step_question_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.RunPython(migrate_existing_threads, migrations.RunPython.noop),
    ]
