# Generated by Django 5.2.17 on 2026-09-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_stepquestionmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('paused', 'Приостановлено'), ('completed', 'Завершено'), ('removed', 'Снято')], default='active', max_length=16),
        ),
    ]
