# Generated by Django 5.2.17 on 2026-09-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('failures', models.PositiveSmallIntegerField(default=0)),
                ('window_started_at', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
