# Generated by Django 5.2.17 on 2026-09-23 16:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('grade_min', models.PositiveSmallIntegerField(default=1)),
                ('grade_max', models.PositiveSmallIntegerField(default=9)),
                ('is_archived', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CourseRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('grade_min', models.PositiveSmallIntegerField()),
                ('grade_max', models.PositiveSmallIntegerField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='courses.course')),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-version',),
            },
        ),
        migrations.AddField(
            model_name='course',
            name='latest_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_for_courses', to='courses.courserevision'),
        ),
        migrations.CreateModel(
            name='DraftStep',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_key', models.CharField(max_length=64)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('position', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('content', models.JSONField(default=dict)),
                ('max_score', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_steps', to='courses.course')),
            ],
            options={
                'ordering': ('position', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='StepRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_draft_step_id', models.UUIDField()),
                ('type_key', models.CharField(max_length=64)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('position', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('content', models.JSONField(default=dict)),
                ('max_score', models.PositiveIntegerField()),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='courses.courserevision')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.AddConstraint(
            model_name='courserevision',
            constraint=models.UniqueConstraint(fields=('course', 'version'), name='unique_course_revision_version'),
        ),
        migrations.AddConstraint(
            model_name='draftstep',
            constraint=models.UniqueConstraint(fields=('course', 'position'), name='unique_draft_step_position'),
        ),
        migrations.AddConstraint(
            model_name='steprevision',
            constraint=models.UniqueConstraint(fields=('revision', 'position'), name='unique_revision_step_position'),
        ),
    ]
