# Generated by Django 5.2.17 on 2026-09-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_curriculum_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='banner_image',
            field=models.FileField(blank=True, default='', upload_to='course-banners/'),
        ),
        migrations.AddField(
            model_name='courserevision',
            name='banner_image',
            field=models.FileField(blank=True, default='', upload_to='course-banners/'),
        ),
    ]
